version: '3.7'
services:
    fibonacci_app:
        build: .
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        volumes:
            - .:/app
        command: npm run dev
        links:
            - fibonacci_redis
            - fibonacci_rabbitmq
        network_mode: bridge
        env_file:
            - .env
    fibonacci_redis:
        image: redis:alpine
        network_mode: bridge
        ports:
            - '6379:6379'
    fibonacci_rabbitmq:
        image: rabbitmq:3
        ports:
            - '5672:5672'
        network_mode: bridge
